# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-12-21 23:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='state',
            field=models.CharField(default=None, max_length=120),
            preserve_default=False,
        ),
    ]
