# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-01-01 22:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='default_payment',
            field=models.BooleanField(default=True),
        ),
    ]
