# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-12-19 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20191219_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('shipped', 'Shipped'), ('paid', 'Paid'), ('created', 'Created'), ('refunded', 'Refunded')], default='created', max_length=120),
        ),
    ]
