# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-12-19 23:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20191219_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('shipped', 'Shipped'), ('refunded', 'Refunded'), ('created', 'Created'), ('paid', 'Paid')], default='created', max_length=120),
        ),
    ]
