# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-12-21 23:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20191220_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('refunded', 'Refunded'), ('shipped', 'Shipped'), ('paid', 'Paid'), ('created', 'Created')], default='created', max_length=120),
        ),
    ]
