# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-12-21 23:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20191221_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('refunded', 'Refunded'), ('paid', 'Paid'), ('shipped', 'Shipped')], default='created', max_length=120),
        ),
    ]
