# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-12-28 19:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20191222_0307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[(b'refunded', b'Refunded'), (b'shipped', b'Shipped'), (b'created', b'Created'), (b'paid', b'Paid')], default=b'created', max_length=120),
        ),
    ]
